In [ ]:
PYTHON

In [ ]:
#2. Use map to double all the elements in the list: [1, 2, 3, 4, 5].

In [2]:
numbers = [1, 2, 3, 4, 5]
doubled_numbers = list(map(lambda x: x * 2, numbers))
print(doubled_numbers)

[2, 4, 6, 8, 10]


In [ ]:
#3. Use filter to extract all even numbers from the list: [10, 15, 20, 25, 30].

In [3]:
numbers = [10, 15, 20, 25, 30]
# extract even numbers
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print("Even numbers:", even_numbers)

Even numbers: [10, 20, 30]


In [ ]:
#5. Write a function that takes a variable number of arguments (*args) and returns
their sum.

In [4]:
def sum_of_args(*args):
    return sum(args)
result = sum_of_args(50,100,125,150)
print(result)


425


In [ ]:
#10.Write a program to print the first 10 natural numbers using a for loop.

In [5]:
# Program to print the first 10 natural numbers
for i in range(1, 11):
    print(i)


1
2
3
4
5
6
7
8
9
10


In [ ]:
#11.Write a program to calculate the sum of all numbers in a list: [5, 10, 15, 20] using a for loop

In [6]:
numbers = [5, 10, 15, 20]
total_sum = 0
for num in numbers:
    total_sum += num

print(total_sum)


50


In [ ]:
#12.Write a Python program to print the multiplication table of a given number using a while loop.

In [9]:
num = int(input("Enter multiplication table: "))
i = 1

print(f"Multiplication table of is  {num}:")
while i <= 10:
    print(f"{num} x {i} = {num * i}")
    i += 1


Enter multiplication table:  2


Multiplication table of is  2:
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


In [ ]:
#13.Write a program to find the factorial of a number using a while loop.

In [12]:
num = int(input("number is  to find its factorial: "))
factorial = 1
i = 1
while i <= num:
    factorial *= i
    i += 1
print(f"The factorial of {num} is {factorial}" )


number is  to find its factorial:  8


The factorial of 8 is 40320


In [ ]:
#14.Write a Python program to check if a number entered by the user is even or odd.

In [13]:
#for even number 
number = int(input("Enter a number: "))
if number % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")

Enter a number:  4


The number is even.


In [14]:
#for odd number 
number = int(input("Enter a number: "))
if number % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")

Enter a number:  5


The number is odd.


In [ ]:
#17 .Write a function to find the maximum of three numbers entered by the user.

In [15]:
def max_of_three(a, b, c):
    return max(a, b, c)
result=max_of_three(150,100,200)
print("The max of three number",result)

The max of three number 200


In [ ]:
#18.Write a function that takes a list of numbers and returns the largest number

In [17]:
def find_largest(numbers):
    return max(numbers)
numbers_list = [2,5,6,8,9,10,15,18,25]
largest_number = find_largest(numbers_list)
print(f"The largest number in the list is: {largest_number}")


The largest number in the list is: 25


In [ ]:
#19.Write a Python program to reverse a string using a for loop.

In [18]:
def reverse_string(s):
    reversed_str = ""
    for char in s:
        reversed_str = char + reversed_str
    return reversed_str
input_string = input("Enter a string to reverse: ")
reversed_string = reverse_string(input_string)
print(f"The reversed string is: {reversed_string}")


Enter a string to reverse:  Dinesh


The reversed string is: hseniD


In [ ]:
#20.Write a Python program to count the number of vowels in a string entered by the user.

In [23]:
def count_vowels(a):
    vowels = "aeiou"
    count = 0
    for char in a:
        if char in vowels:
            count += 1
    return count
input_string = input("Enter a string to count the vowels: ")
vowel_count = count_vowels(input_string)
print(f"The number of vowels in the string : {vowel_count}")



Enter a string to count the vowels:  dinesh


The number of vowels in the string : 2


In [ ]:
NumPy Questions

In [ ]:
#1. Create a NumPy array of zeros with shape (3, 4)

In [26]:
import numpy as np
zeros_array = np.zeros((3, 4))
print(zeros_array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#2. Create a NumPy array of ones with shape (2, 5).

In [27]:
import numpy as np
ones_array = np.ones((2, 5))
print(ones_array)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
import numpy as np
matrix = np.arange(1, 11)
print(matrix)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#4. Create a NumPy array with numbers from 0 to 1 (inclusive) with a step size of 0.1 using np.arange().

In [30]:
import numpy as np
array = np.arange(0, 1.1, 0.1)
print(array)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
##7. Compute the sum of all elements in the array np.array([2, 3, 4, 5, 6]).

In [32]:
import numpy as np
array = np.array([2, 3, 4, 5, 6])
sum_of_elements = np.sum(array)
print(sum_of_elements)


20


In [ ]:
#8. Find the minimum value in the array np.array([1, 5, 9, 3, 6]) using np.min()

In [34]:
import numpy as np
array=np.array([1,5,9,3,6])
print(np.min(array))

1


In [ ]:
#9. Find the maximum value in the array np.array([1, 5, 9, 3, 6]) using np.max().

In [35]:
import numpy as np
array=np.array([1,5,9,3,6])
print(np.max(array))

9


In [ ]:
#11.Generate an array of 5 random integers between 10 and 50 using np.random.randint().


In [37]:
import numpy as np
array=np.random.randint(10,50,5)
print(array)

[35 34 37 11 28]


In [ ]:
#19.Reshape a 1D array [1, 2, 3, 4, 5, 6] into a 2x3 matrix using np.reshape()

In [38]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
#20.Slice the first two elements from the array np.array([10, 20, 30, 40, 50]).

In [39]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[:2])

[10 20]
